allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - geosite:private
  - geosite:cn
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geox-url:
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-Country.mmdb
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5346 | 3.947MB
  network: ws
  port: 80
  server: cc6cbcb9-sv0xs0-sxx3hh-1m7j8.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5346 | 3.947MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 91acf762-a4ea-11ef-b090-f23c91cfbbc9
  ws-opts:
    headers:
      Host: cc6cbcb9-sv0xs0-sxx3hh-1m7j8.hk3.p5pv.com
    path: /
- alterId: 0
  cipher: auto
  name: 🇭🇰HK-1.65.139.59-0175 | 3.775MB
  network: ws
  port: 8080
  server: 2abb3c67-swkhs0-t1457r-g53t.hgc1.tcpbbr.net
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b778e4ae-1458-11ec-a8bf-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 2abb3c67-swkhs0-t1457r-g53t.hgc1.tcpbbr.net
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5429 | 3.722MB
  network: ws
  port: 80
  server: e20770f7-sv2sg0-t21ryz-1rk0u.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5429 | 3.722MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ae403676-1f72-11ef-98df-f23c91cfbbc9
  ws-opts:
    headers:
      Host: e20770f7-sv2sg0-t21ryz-1rk0u.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5333 | 3.61MB
  network: ws
  port: 80
  server: a58b4c29-sv4n40-syfj90-1r9dt.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5333 | 3.61MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: de003c72-0157-11ef-86da-f23c91cfbbc9
  ws-opts:
    headers:
      Host: a58b4c29-sv4n40-syfj90-1r9dt.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5341 | 3.54MB
  network: ws
  port: 80
  server: 06eb7c64-sv2sg0-svxfqo-1hfyu.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5341 | 3.54MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ab0147e4-e673-11ee-8058-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 06eb7c64-sv2sg0-svxfqo-1hfyu.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5354 | 3.51MB
  network: ws
  port: 80
  server: 6bbeaaf6-sv4n40-t8tsp0-1szmi.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5354 | 3.51MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ba151628-b3a2-11ef-bdb9-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 6bbeaaf6-sv4n40-t8tsp0-1szmi.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5350 | 3.499MB
  network: ws
  port: 80
  server: a1a13b07-sv4n40-svvk7h-1tgdw.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5350 | 3.499MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: a19397b8-f7fa-11ef-836a-f23c913c8d2b
  ws-opts:
    headers:
      Host: a1a13b07-sv4n40-svvk7h-1tgdw.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5361 | 3.464MB
  network: ws
  port: 80
  server: ac5c4ff4-sv2sg0-swskl4-1rh01.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5361 | 3.464MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 4c0ba4a2-1510-11ef-ba65-f23c91cfbbc9
  ws-opts:
    headers:
      Host: ac5c4ff4-sv2sg0-swskl4-1rh01.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5343 | 3.447MB
  network: ws
  port: 80
  server: 8e42f8d1-sv0xs0-szxh9w-46gc.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5343 | 3.447MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 225d1cca-d744-11ef-b790-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 8e42f8d1-sv0xs0-szxh9w-46gc.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5396 | 3.434MB
  network: ws
  port: 80
  server: bdef0bf0-sv2sg0-sx8o7m-89x.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5396 | 3.434MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: d507f0a8-049d-11f0-90e2-f23c913c8d2b
  ws-opts:
    headers:
      Host: bdef0bf0-sv2sg0-sx8o7m-89x.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5285 | 3.4MB
  network: ws
  port: 80
  server: e7faf98f-sv2sg0-t802lu-1p9qc.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5285 | 3.4MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 37e9a0f8-8ade-11ee-b03a-f23c913c8d2b
  ws-opts:
    headers:
      Host: e7faf98f-sv2sg0-t802lu-1p9qc.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5395 | 3.376MB
  network: ws
  port: 80
  server: bae1d3e4-sv4n40-t5hlsw-1b3xq.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5395 | 3.376MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b297d1ea-976f-11eb-8673-f23c9164ca5d
  ws-opts:
    headers:
      Host: bae1d3e4-sv4n40-t5hlsw-1b3xq.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5399 | 3.347MB
  network: ws
  port: 80
  server: 1716e7d1-sucv40-tcum62-se45.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5399 | 3.347MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: d076280a-0d5f-11f0-8a7b-f23c913c8d2b
  ws-opts:
    headers:
      Host: 1716e7d1-sucv40-tcum62-se45.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5390 | 3.304MB
  network: ws
  port: 80
  server: 9e6fe842-sv4n40-t6ctgc-1s3hd.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5390 | 3.304MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 1c641c86-5078-11ef-a585-f23c9164ca5d
  ws-opts:
    headers:
      Host: 9e6fe842-sv4n40-t6ctgc-1s3hd.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5366 | 3.28MB
  network: ws
  port: 80
  server: fe32008f-sv2sg0-t83wtx-2rrb.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5366 | 3.28MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ba64cdc5-c79a-326d-8e63-6903be8183a1
  ws-opts:
    headers:
      Host: fe32008f-sv2sg0-t83wtx-2rrb.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5347 | 3.25MB
  network: ws
  port: 80
  server: 5a535e9d-sv2sg0-t15duc-1nsdp.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5347 | 3.25MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 70e061f6-796a-11ee-8f26-f23c913c8d2b
  ws-opts:
    headers:
      Host: 5a535e9d-sv2sg0-t15duc-1nsdp.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5304 | 3.219MB
  network: ws
  port: 80
  server: 7f346235-sv4n40-t76x2i-wj6v.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5304 | 3.219MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 847c03b2-0a9d-11eb-a8bf-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 7f346235-sv4n40-t76x2i-wj6v.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5449 | 3.211MB
  network: ws
  port: 80
  server: 25109257-sv4n40-t5qfe2-1khwf.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5449 | 3.211MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 92bd8c68-6434-11ee-b644-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 25109257-sv4n40-t5qfe2-1khwf.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5421 | 3.158MB
  network: ws
  port: 80
  server: c425f654-sv2sg0-sz578n-1pw2y.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5421 | 3.158MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8815622e-7598-11ef-a01c-f23c913c8d2b
  ws-opts:
    headers:
      Host: c425f654-sv2sg0-sz578n-1pw2y.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5313 | 3.153MB
  network: ws
  port: 80
  server: ac1aede0-sv2sg0-t5qfe2-1khwf.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5313 | 3.153MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 92bd8c68-6434-11ee-b644-f23c91cfbbc9
  ws-opts:
    headers:
      Host: ac1aede0-sv2sg0-t5qfe2-1khwf.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-42.2.113.136-0404 | 3.138MB
  network: ws
  port: 80
  server: af4e4239-sv2sg0-svpmdc-nx3b.hk.p5pv.com
  servername: 🇭🇰HK-42.2.113.136-0404 | 3.138MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 32315324-cf6b-11ed-979b-f23c9164ca5d
  ws-opts:
    headers:
      Host: af4e4239-sv2sg0-svpmdc-nx3b.hk.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5372 | 3.08MB
  network: ws
  port: 80
  server: 9baf7b79-sv0xs0-td5fm5-4dl0.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5372 | 3.08MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 56b05600-e140-11ec-a3de-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 9baf7b79-sv0xs0-td5fm5-4dl0.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5375 | 3.076MB
  network: ws
  port: 80
  server: 87a8ce25-sv2sg0-tbicd9-1go3q.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5375 | 3.076MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 19dd9c70-e4a5-11ed-8347-f23c9164ca5d
  ws-opts:
    headers:
      Host: 87a8ce25-sv2sg0-tbicd9-1go3q.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5430 | 3.069MB
  network: ws
  port: 80
  server: 8b31a356-sv2sg0-tb224g-1h0r9.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5430 | 3.069MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 9bfd0dde-957e-11ec-a8bf-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 8b31a356-sv2sg0-tb224g-1h0r9.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5391 | 3.037MB
  network: ws
  port: 80
  server: 97ec248c-sv2sg0-t1l34b-s6zq.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5391 | 3.037MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b989d57a-ccc3-11ee-b3a0-f23c9164ca5d
  ws-opts:
    headers:
      Host: 97ec248c-sv2sg0-t1l34b-s6zq.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5409 | 3.012MB
  network: ws
  port: 80
  server: 04165a49-sv2sg0-t5cryd-4w8.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5409 | 3.012MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ba7a37e3-033a-e1ab-06f6-9027aa4630f5
  ws-opts:
    headers:
      Host: 04165a49-sv2sg0-t5cryd-4w8.hk3.p5pv.com
    path: /
- alterId: 0
  cipher: auto
  name: 🇭🇰HK-1.65.139.59-0702 | 3.003MB
  network: ws
  port: 8080
  server: 507dabb3-swtr40-sxzp1j-1irfn.hgc1.tcpbbr.net
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: a33115b6-75fa-11ed-8826-f23c9164ca5d
  ws-opts:
    headers:
      Host: 507dabb3-swtr40-sxzp1j-1irfn.hgc1.tcpbbr.net
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5292 | 2.998MB
  network: ws
  port: 80
  server: 51a08fff-sv4n40-sy1a0y-1iyov.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5292 | 2.998MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 33629870-e57e-11ec-bb74-f23c9164ca5d
  ws-opts:
    headers:
      Host: 51a08fff-sv4n40-sy1a0y-1iyov.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5428 | 2.945MB
  network: ws
  port: 80
  server: f0278492-sv2sg0-tcvree-129gb.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5428 | 2.945MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 88994e12-009f-11eb-8684-f23c913c8d2b
  ws-opts:
    headers:
      Host: f0278492-sv2sg0-tcvree-129gb.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5315 | 2.929MB
  network: ws
  port: 80
  server: 8546e833-sv4n40-t4v3jz-1k8ga.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5315 | 2.929MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: f860f2da-5035-11ed-bb74-f23c9164ca5d
  ws-opts:
    headers:
      Host: 8546e833-sv4n40-t4v3jz-1k8ga.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5362 | 2.91MB
  network: ws
  port: 80
  server: 5e4f31de-sv0xs0-sv0wpw-17xo8.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5362 | 2.91MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b4e40aa2-74a1-11ed-b0b5-f23c9164ca5d
  ws-opts:
    headers:
      Host: 5e4f31de-sv0xs0-sv0wpw-17xo8.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5423 | 2.897MB
  network: ws
  port: 80
  server: ae709d15-sv0xs0-svim0o-1slop.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5423 | 2.897MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 520b9126-9870-11ef-81b0-f23c9164ca5d
  ws-opts:
    headers:
      Host: ae709d15-sv0xs0-svim0o-1slop.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5407 | 2.89MB
  network: ws
  port: 80
  server: b1601217-sv2sg0-tcdlur-1qwom.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5407 | 2.89MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8d0ec7cc-eefa-11ee-9b59-f23c91cfbbc9
  ws-opts:
    headers:
      Host: b1601217-sv2sg0-tcdlur-1qwom.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5432 | 2.873MB
  network: ws
  port: 80
  server: a142295f-sv2sg0-t04f46-1hvn1.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5432 | 2.873MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8d05476e-ae88-11ed-8543-f23c913c8d2b
  ws-opts:
    headers:
      Host: a142295f-sv2sg0-t04f46-1hvn1.hk3.p5pv.com
    path: /
proxy-groups:
- name: 选择代理
  proxies:
  - 香港-手动选择
  - 香港-自动优选
  - 香港-负载均衡
  - DIRECT
  type: select
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-手动选择
  timeout: 2000
  type: select
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-自动优选
  timeout: 2000
  tolerance: 50
  type: url-test
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-负载均衡
  strategy: consistent-hashing
  timeout: 2000
  type: load-balance
  url: http://www.msftncsi.com/ncsi.txt
rule-providers:
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
rules:
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,ghproxy.com,DIRECT
- RULE-SET,applications,DIRECT
- GEOSITE,category-ads-all,REJECT
- GEOSITE,bing,选择代理
- GEOSITE,microsoft,选择代理
- GEOSITE,private,DIRECT
- GEOIP,lan,DIRECT
- GEOIP,private,DIRECT
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,geolocation-!cn,选择代理
- GEOIP,cn,DIRECT
- MATCH,选择代理
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
