allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - geosite:private
  - geosite:cn
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geox-url:
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-Country.mmdb
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-128-gcm
  name: 🇭🇰HK-156.225.22.213-4932 | 0.58MB
  password: rGDbiF7gtx5TWt4r4VjneQ==
  port: 552
  server: 156.225.22.213
  type: ss
- alterId: 0
  cipher: auto
  name: 🇭🇰1 |  1.8MB/s|15%|Disney|Yout...
  network: ws
  port: 8080
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  ws-opts:
    headers:
      Host: broadcastlv.chat.bilibili.com
    path: /
- alterId: 2
  cipher: auto
  name: 香港|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
- cipher: aes-256-gcm
  name: 🇭🇰 香港2|@ripaojiedian
  password: f917888c6f39
  plugin: v2ray-plugin
  plugin-opts:
    host: hkxwv1-5.dsjsapi.com
    mode: websocket
    mux: true
    path: /rxoasyex
    skip-cert-verify: false
    tls: true
  port: 636
  server: 121.127.231.200
  tfo: false
  type: ss
- cipher: aes-256-gcm
  name: 🇭🇰 香港3|@ripaojiedian
  password: DWRHI0W4F0RELXHP
  port: 15012
  server: 8tv68qhq.slashdevslashnetslashtun.net
  tfo: false
  type: ss
- alterId: 0
  cipher: auto
  name: 香港4|@ripaojiedian
  network: ws
  port: '8080'
  server: 977fb705-symkg0-t02swp-fa3p.hgc1.tcpbbr.net
  servername: ''
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vmess
  uuid: 905fcd78-866c-81e1-3cb8-1beb59d661ab
  ws-opts:
    headers:
      Host: broadcastlv.chat.bilibili.com
    path: /
- cipher: aes-256-gcm
  name: 🇭🇰 香港5|@ripaojiedian
  password: 1FE8UX5KHGYBLYMU
  port: 15015
  server: ti3hyra4.slashdevslashnetslashtun.net
  tfo: false
  type: ss
- alterId: 0
  cipher: auto
  name: 香港v2|@ripaojiedian
  network: kcp
  port: '34833'
  server: 47.76.28.43
  servername: ''
  tls: false
  type: vmess
  uuid: dd0d30ae-a4d1-4d1e-8553-42bfff66fd27
proxy-groups:
- name: 选择代理
  proxies:
  - 香港-手动选择
  - 香港-自动优选
  - 香港-负载均衡
  - DIRECT
  type: select
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-手动选择
  timeout: 2000
  type: select
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-自动优选
  timeout: 2000
  tolerance: 50
  type: url-test
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-负载均衡
  strategy: consistent-hashing
  timeout: 2000
  type: load-balance
  url: http://www.msftncsi.com/ncsi.txt
rule-providers:
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
rules:
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,ghproxy.com,DIRECT
- RULE-SET,applications,DIRECT
- GEOSITE,category-ads-all,REJECT
- GEOSITE,bing,选择代理
- GEOSITE,microsoft,选择代理
- GEOSITE,private,DIRECT
- GEOIP,lan,DIRECT
- GEOIP,private,DIRECT
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,geolocation-!cn,选择代理
- GEOIP,cn,DIRECT
- MATCH,选择代理
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
