allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - geosite:private
  - geosite:cn
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geox-url:
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-Country.mmdb
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- name: 🇭🇰HK-20.2.156.38-5574 | 10.615MB
  password: 6087d8e3-ea9e-48eb-8217-6050ff752f56
  port: 443
  server: il.mjt000.com
  skip-cert-verify: false
  sni: il.mjt000.com
  type: trojan
- alterId: 0
  cipher: auto
  name: 🇭🇰HK-1.36.218.184-0835 | 8.514MB
  network: ws
  port: 8080
  server: 338b2185-sw1z40-sw51rj-hkb8.hgc1.tcpbbr.net
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 21a70fd2-c69c-11eb-8673-f23c9164ca5d
  ws-opts:
    headers:
      Host: broadcastlv.chat.bilibili.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-42.2.113.136-0364 | 8.418MB
  network: ws
  port: 80
  server: 66500699-sv2sg0-sx8y86-uvgv.hk.p5pv.com
  servername: 🇭🇰HK-42.2.113.136-0364 | 8.418MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ee67070a-ceb2-11ed-bb7d-f23c913c8d2b
  ws-opts:
    headers:
      Host: 66500699-sv2sg0-sx8y86-uvgv.hk.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-42.2.113.136-5686 | 8.115MB
  network: ws
  port: 80
  server: ac759499-sv2sg0-sw26q2-php4.hk.p5pv.com
  servername: 🇭🇰HK-42.2.113.136-5686 | 8.115MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: c648ecc0-838a-11ed-bd81-f23c913c8d2b
  ws-opts:
    headers:
      Host: ac759499-sv2sg0-sw26q2-php4.hk.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-42.2.113.136-5685 | 7.29MB
  network: ws
  port: 80
  server: 691232a1-sv6hs0-sx8y86-uvgv.hk.p5pv.com
  servername: 🇭🇰HK-42.2.113.136-5685 | 7.29MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ee67070a-ceb2-11ed-bb7d-f23c913c8d2b
  ws-opts:
    headers:
      Host: 691232a1-sv6hs0-sx8y86-uvgv.hk.p5pv.com
    path: /
- alterId: 0
  cipher: auto
  name: 🇭🇰HK-1.36.218.184-5692 | 7.005MB
  network: ws
  port: 8080
  server: 338b2185-sw1z40-sw51rj-hkb8.hgc1.tcpbbr.net
  servername: 🇭🇰HK-1.36.218.184-5692 | 7.005MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 21a70fd2-c69c-11eb-8673-f23c9164ca5d
  ws-opts:
    headers:
      Host: 338b2185-sw1z40-sw51rj-hkb8.hgc1.tcpbbr.net
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5688 | 4.251MB
  network: ws
  port: 80
  server: be1c3b6c-sv0xs0-sw26q2-php4.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5688 | 4.251MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: c648ecc0-838a-11ed-bd81-f23c913c8d2b
  ws-opts:
    headers:
      Host: be1c3b6c-sv0xs0-sw26q2-php4.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5689 | 3.864MB
  network: ws
  port: 80
  server: a0ae8f27-sv4n40-sw5wi7-ufc0.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5689 | 3.864MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 22308988-8548-11ea-a22e-f23c91cfbbc9
  ws-opts:
    headers:
      Host: a0ae8f27-sv4n40-sw5wi7-ufc0.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5693 | 3.727MB
  network: ws
  port: 80
  server: 4e909a9d-sv2sg0-sw26q2-php4.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5693 | 3.727MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: c648ecc0-838a-11ed-bd81-f23c913c8d2b
  ws-opts:
    headers:
      Host: 4e909a9d-sv2sg0-sw26q2-php4.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5690 | 3.7MB
  network: ws
  port: 80
  server: 4f8acdc9-sv0xs0-sw5wi7-ufc0.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5690 | 3.7MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 22308988-8548-11ea-a22e-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 4f8acdc9-sv0xs0-sw5wi7-ufc0.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5684 | 3.288MB
  network: ws
  port: 80
  server: 77d7b6e4-sv2sg0-sw5wi7-ufc0.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5684 | 3.288MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 22308988-8548-11ea-a22e-f23c91cfbbc9
  ws-opts:
    headers:
      Host: 77d7b6e4-sv2sg0-sw5wi7-ufc0.hk3.p5pv.com
    path: /
- alterId: 2
  cipher: auto
  name: 🇭🇰HK-1.65.202.165-5691 | 2.536MB
  network: ws
  port: 80
  server: 3fa5b1b6-sv2sg0-sx8y86-uvgv.hk3.p5pv.com
  servername: 🇭🇰HK-1.65.202.165-5691 | 2.536MB
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ee67070a-ceb2-11ed-bb7d-f23c913c8d2b
  ws-opts:
    headers:
      Host: 3fa5b1b6-sv2sg0-sx8y86-uvgv.hk3.p5pv.com
    path: /
- cipher: chacha20-ietf-poly1305
  name: 0|🇭🇰 香港 101 | 1x HK
  password: 0fa3093d-f27e-45b3-82ca-e17ba9eee18d
  port: 36141
  server: freea.glyphara.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 0|🇭🇰 香港 102 | 1x HK
  password: 0fa3093d-f27e-45b3-82ca-e17ba9eee18d
  port: 36143
  server: freea.glyphara.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 0|🇭🇰 香港住宅IP 103 | 1x HK
  password: 0fa3093d-f27e-45b3-82ca-e17ba9eee18d
  port: 36145
  server: freea.glyphara.com
  type: ss
  udp: true
- alterId: 0
  cipher: auto
  name: 2|🇭🇰1 |  1.8MB/s|15%|Disney|Yout...
  network: ws
  port: 8080
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  ws-opts:
    headers:
      Host: broadcastlv.chat.bilibili.com
    path: /
- cipher: chacha20-ietf-poly1305
  name: 3|🇭🇰香港 101 | 1x HK
  password: 5b4a3aec-e233-4e58-8c7e-d2cfcfe3d102
  port: 31141
  server: freem.vidalith.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 3|🇭🇰香港 102 | 1x HK
  password: 5b4a3aec-e233-4e58-8c7e-d2cfcfe3d102
  port: 31143
  server: freem.vidalith.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 3|🇭🇰香港家宽 103 | 1x HK
  password: 5b4a3aec-e233-4e58-8c7e-d2cfcfe3d102
  port: 31145
  server: freem.vidalith.com
  type: ss
  udp: true
- alterId: 0
  cipher: auto
  name: 13|🇭🇰 香港7|@ripaojiedian
  port: 20332
  server: 43.247.135.2
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vmess
  uuid: 8037ce00-c860-4213-b888-be5c7ed6ea48
- cipher: chacha20-ietf-poly1305
  name: 13|🇭🇰 香港2|@ripaojiedian
  password: 1450cecfb93f
  plugin: v2ray-plugin
  plugin-opts:
    host: kh36v1.pmxiaonan.xyz
    mode: websocket
    mux: true
    path: /simieepvt
    skip-cert-verify: false
    tls: true
  port: 15056
  server: 121.127.231.229
  tfo: false
  type: ss
- name: 13,14|香港3|@ripaojiedian
  network: tcp
  password: 85f133142f04dbf6547da33895cfabb3
  port: 39001
  server: 125.94.40.221
  skip-cert-verify: true
  sni: www.yrtok.com
  type: trojan
- name: 13,14|香港4|@ripaojiedian
  network: tcp
  password: 85f133142f04dbf6547da33895cfabb3
  port: 39001
  server: 113.99.140.184
  skip-cert-verify: true
  sni: www.yrtok.com
  type: trojan
- alterId: 2
  cipher: auto
  name: 13,14|香港6|@ripaojiedian
  network: ws
  port: '30809'
  server: v9.heduian.link
  servername: ''
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: baidu.com
    path: /oooo
- alterId: 0
  cipher: auto
  name: 14|香港7|@ripaojiedian
  network: tcp
  port: '20332'
  server: 43.247.135.2
  servername: ''
  tls: false
  type: vmess
  uuid: 8037ce00-c860-4213-b888-be5c7ed6ea48
- alterId: 32
  cipher: auto
  h2-opts: {}
  http-opts: {}
  name: VMESS-美国>香港-NF解锁自制剧-ChatGPT-YouTube-vc.fly.dev:443
  network: ws
  port: 443
  server: vc.fly.dev
  servername: vc.fly.dev
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 35379219-6535-4f2e-a4fe-3e44f61e0eee
  ws-opts:
    headers:
      HOST: vc.fly.dev
    path: /vc
proxy-groups:
- name: 选择代理
  proxies:
  - 香港-手动选择
  - 香港-自动优选
  - 香港-负载均衡
  - DIRECT
  type: select
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-手动选择
  timeout: 2000
  type: select
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-自动优选
  timeout: 2000
  tolerance: 50
  type: url-test
  url: http://www.msftncsi.com/ncsi.txt
- include-all-proxies: true
  interval: 60
  max-failed-times: 3
  name: 香港-负载均衡
  strategy: consistent-hashing
  timeout: 2000
  type: load-balance
  url: http://www.msftncsi.com/ncsi.txt
rule-providers:
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
rules:
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,ghproxy.com,DIRECT
- RULE-SET,applications,DIRECT
- GEOSITE,category-ads-all,REJECT
- GEOSITE,bing,选择代理
- GEOSITE,microsoft,选择代理
- GEOSITE,private,DIRECT
- GEOIP,lan,DIRECT
- GEOIP,private,DIRECT
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,geolocation-!cn,选择代理
- GEOIP,cn,DIRECT
- MATCH,选择代理
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
